### ISSUE TITLE
Error: Unable to detect compiler type

### ISSUE THREAD

**Issue by KhafraDev** [mscdex/buildcheck#1]
Hey, when installing esqlite v0.0.5 I've been getting this issue on Windows 10:

```
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at new BuildEnvironment (\buildcheck\lib\index.js:133:15)
```

I have the deps required and it works fine on an Ubuntu machine so I decided to dig a little deeper and found the issue to be this line:
https://github.com/mscdex/buildcheck/blob/c37e6e9ebacc177d7793d157295e76062afb4c86/lib/findvs.js#L168
as the path `...Microsoft.VCToolsVersion.v141.default.txt` does not exist, however the path `...Microsoft.VCToolsVersion.default.txt` does exist for me (modifying the package, installing esqlite@0.0.5, and manually running the installation script works afterwards).

Thank you! :)

**Comment by jeffrson** [comment]
Should this be fixed? I get this now with yarn 3.2 - Windows 10, Node 17.9.0, when installing ssh2 (via cpu-features).

yarn 1 does not show such obvious error

**Comment by jeffrson** [comment]
So this is most probably because of the algorithm needs `Find-VisualStudio.cs`, which is not available with yarn 3.2. It can be "fixed" by adding the following section to package.json:

```
  "dependenciesMeta": {
    "buildcheck@0.0.4": {
      "unplugged": true
    }
  }
```

Hopefully this will become unnecessary once prebuilt artifacts of cpu-features will be available.

**Comment by mscdex** [comment]
@jeffrson I don't understand what you mean. "Find-VisualStudio.cs" is provided by this package, not yarn, unless you're saying yarn is removing files from packages?

**Comment by jeffrson** [comment]
To be a bit more verbose:
Yarn2+ usually has a module installation strategy called "Plug'n'Play" (https://yarnpkg.com/features/pnp). All dependencies are being kept in zip files from where they are read during runtime.

There are exceptions for files that need to be built. For buildcheck, however, yarn cannot know that some internal file will be requested from outside and (in contrary to 'require') it does not support access to this file inside the zip this way.

The "dependenciesMeta" block gives a hint to unpack buildcheck, such that powershell will find the file.
